import Head from "next/head";

const Header = () => {
  return (
    <Head>
      {/* <title>!VARIZ</title> */}
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="stylesheet" href="/styles/bootstrap.css" />
      <link href="https://pro.fontawesome.com/releases/v5.15.0/css/all.css" rel="stylesheet"></link>
    </Head>
  );
};

export default Header;
